name: unittests

on: [ push, pull_request ]

jobs:
  unittests:
    name: '[PHP ${{ matrix.php-version }} | Neos ${{ matrix.neos-version }}] Unit Tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 7.4, 8.3 ]
        neos-version: [ 7.3, 8.3 ]
        exclude:
          - php-version: 7.4
            neos-version: 8.3

    env:
      APP_ENV: true
      FLOW_CONTEXT: Testing/Unit
      NEOS_DIST_FOLDER: neos-base-distribution

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
          ini-values: opcache.fast_shutdown=0

      - name: Install composer dependencies
        run: composer create-project neos/neos-base-distribution ${{ env.NEOS_DIST_FOLDER }} --prefer-dist --no-progress --no-install --no-scripts "^${{ matrix.neos-version }}"

      - name: "Allow neos composer plugin"
        run: composer config --no-plugins allow-plugins.neos/composer-plugin true
        working-directory: ${{ env.NEOS_DIST_FOLDER }}

      - name: "Require behat in compatible version"
        run: composer require --dev --no-update "neos/behat:@dev"
        working-directory: ${{ env.NEOS_DIST_FOLDER }}

      - name: "Install project"
        run: composer install
        working-directory: ${{ env.NEOS_DIST_FOLDER }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.NEOS_DIST_FOLDER }}/DistributionPackages/Netlogix.UserManagement

      - name: Install netlogix/usermanagement
        run: composer require netlogix/usermanagement:@dev
        working-directory: ${{ env.NEOS_DIST_FOLDER }}

      - name: Run tests
        run: bin/phpunit -c DistributionPackages/Netlogix.UserManagement/phpunit.xml.dist --testsuite="Unit" --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
        working-directory: ${{ env.NEOS_DIST_FOLDER }}
