name: unittests

on: [ push, pull_request ]

jobs:
  unittests:
    name: '[PHP ${{ matrix.php-version }} | Neos ${{ matrix.neos-version }}] Unit Tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        neos-version: [ 4.3, 5.3 ]

    env:
      APP_ENV: true
      FLOW_CONTEXT: Testing/Unit
      NEOS_DIST_FOLDER: neos-base-distribution

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
          ini-values: opcache.fast_shutdown=0

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-version }}-flow-${{ matrix.neos-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-version }}-flow-${{ matrix.neos-version }}-composer-
            php-${{ matrix.php-version }}-flow-
      - name: Install composer dependencies
        run: composer create-project neos/neos-base-distribution ${{ env.NEOS_DIST_FOLDER }} --prefer-dist --no-progress "^${{ matrix.neos-version }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.NEOS_DIST_FOLDER }}/DistributionPackages/Netlogix.UserManagement

      - name: Install netlogix/usermanagement
        run: composer require netlogix/usermanagement:@dev
        working-directory: ${{ env.NEOS_DIST_FOLDER }}

      - name: Run tests
        run: bin/phpunit -c DistributionPackages/Netlogix.UserManagement/phpunit.xml.dist --testsuite="Unit" --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
        working-directory: ${{ env.NEOS_DIST_FOLDER }}
